In [38]:
# pour installer la librairie pandas à partir de jupyter
%pip install pandas

Requirement already satisfied: pandas in c:\users\dell\anaconda3\lib\site-packages (2.1.4)
Requirement already satisfied: numpy<2,>=1.23.2 in c:\users\dell\anaconda3\lib\site-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\dell\anaconda3\lib\site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\dell\anaconda3\lib\site-packages (from pandas) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in c:\users\dell\anaconda3\lib\site-packages (from pandas) (2023.3)
Requirement already satisfied: six>=1.5 in c:\users\dell\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

In [39]:
# importation de la librairie
import pandas as pd # convention d'appellation

In [40]:
# Pandas utilise deux struct de données: les Series et les DataFrames
# 1- Les Series
# une Series est une structure de données unidimensionnelle, similaire à une colonne dans un tableau ou une liste
# exemple 1 : Créer une Series à partir d'une liste
s = pd.Series([10, 20, 30, 40])
print(s)

0    10
1    20
2    30
3    40
dtype: int64

In [41]:
# exemple 2 : créer une Series avec des index personnalisés
s2 = pd.Series([10, 20, 30, 40], index=['a', 'b', 'c', 'd'])
print(s2)

a    10
b    20
c    30
d    40
dtype: int64

In [42]:
# 2- Les DataFrames
# Une DataFrame est une structure de données bidimensionnelle
# Similaire à une feuille de calcul Excel ou une table SQL
# C'est l'objet principal et le plus utilisé dans pandas
# Il est composé de lignes et de colonnes
# Chaque colonne d'une DataFrame est une Series
# Les colonnes peuvent contenir différents types de données (nombres, chars, booléens, etc...)
# Les index de lignes et noms de colonnes facilitent l'accès et la manipulation des données
# exemple 1 : Créer une DataFrame à partir d'un dictionnaire
data = {
    'Nom': ['Alice', 'Bob', 'Charlie'],
    'Âge': [25, 30, 35],
    'Score': [85, 90, 95]
}
df1 = pd.DataFrame(data)
print(df1)

       Nom  Âge  Score
0    Alice   25     85
1      Bob   30     90
2  Charlie   35     95

In [43]:
# exemple 2 : Créer une DataFrame à partir d'une liste de listes
data = [
    ['Alice', 25, 85],
    ['Bob', 30, 90],
    ['Charlie', 35, 95]
]
df2 = pd.DataFrame(data, columns=['Nom', 'Âge', 'Score'])
print(df2)

       Nom  Âge  Score
0    Alice   25     85
1      Bob   30     90
2  Charlie   35     95

In [44]:
# Exemple de manipulation d'un dataset 
# import du dataset sous forme de DataFrame 
# Ce dataset regroupe les 1000 films les plus populaires répertoriés sur la plateforme IMDB de 2006 à 2016
# sous forme de fichier .csv (comma separated values)
# on peut l'ouvrir à l'aide de pd.read_csv(nom_du_fichier.csv)
# on peut manipuler d'autres types de fichiers (excel,sql....)
df = pd.read_csv("IMDB-Movie-Data.csv")

In [45]:
# méthodes essentielles
# affiche les n premières lignes de la DataFrame, par default (sans arguments) affiche les 5 premières
df.head()
# df.head(10)

,Rank,Title,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore
0,1,Guardians of the Galaxy,"Action,Adventure,Sci-Fi",A group of intergalactic criminals are forced ...,James Gunn,"Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...",2014,121,8.1,757074,333.13,76.0
1,2,Prometheus,"Adventure,Mystery,Sci-Fi","Following clues to the origin of mankind, a te...",Ridley Scott,"Noomi Rapace, Logan Marshall-Green, Michael Fa...",2012,124,7.0,485820,126.46,65.0
2,3,Split,"Horror,Thriller",Three girls are kidnapped by a man with a diag...,M. Night Shyamalan,"James McAvoy, Anya Taylor-Joy, Haley Lu Richar...",2016,117,7.3,157606,138.12,62.0
3,4,Sing,"Animation,Comedy,Family","In a city of humanoid animals, a hustling thea...",Christophe Lourdelet,"Matthew McConaughey,Reese Witherspoon, Seth Ma...",2016,108,7.2,60545,270.32,59.0
4,5,Suicide Squad,"Action,Adventure,Fantasy",A secret government agency recruits some of th...,David Ayer,"Will Smith, Jared Leto, Margot Robbie, Viola D...",2016,123,6.2,393727,325.02,40.0

In [70]:
df.tail() # affiche les n dernieres lignes, par defaut n=5

,Rank,Title,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore,my_rating
990,991,Underworld: Rise of the Lycans,"Action,Adventure,Fantasy",An origins story centered on the centuries-old...,Patrick Tatopoulos,"Rhona Mitra, Michael Sheen, Bill Nighy, Steven...",2009,92,6.6,129708,45.80,44.0,0
991,992,Taare Zameen Par,"Drama,Family,Music",An eight-year-old boy is thought to be a lazy ...,Aamir Khan,"Darsheel Safary, Aamir Khan, Tanay Chheda, Sac...",2007,165,8.5,102697,1.20,42.0,0
992,993,Take Me Home Tonight,"Comedy,Drama,Romance","Four years after graduation, an awkward high s...",Michael Dowse,"Topher Grace, Anna Faris, Dan Fogler, Teresa P...",2011,97,6.3,45419,6.92,NaN,0
993,994,Resident Evil: Afterlife,"Action,Adventure,Horror",While still out to destroy the evil Umbrella C...,Paul W.S. Anderson,"Milla Jovovich, Ali Larter, Wentworth Miller,K...",2010,97,5.9,140900,60.13,37.0,0
994,995,Project X,Comedy,3 high school seniors throw a birthday party t...,Nima Nourizadeh,"Thomas Mann, Oliver Cooper, Jonathan Daniel Br...",2012,88,6.7,164088,54.72,48.0,0
995,996,Secret in Their Eyes,"Crime,Drama,Mystery","A tight-knit team of rising investigators, alo...",Billy Ray,"Chiwetel Ejiofor, Nicole Kidman, Julia Roberts...",2015,111,6.2,27585,NaN,45.0,0
996,997,Hostel: Part II,Horror,Three American college students studying abroa...,Eli Roth,"Lauren German, Heather Matarazzo, Bijou Philli...",2007,94,5.5,73152,17.54,46.0,0
997,998,Step Up 2: The Streets,"Drama,Music,Romance",Romantic sparks occur between two dance studen...,Jon M. Chu,"Robert Hoffman, Briana Evigan, Cassie Ventura,...",2008,98,6.2,70699,58.01,50.0,0
998,999,Search Party,"Adventure,Comedy",A pair of friends embark on a mission to reuni...,Scot Armstrong,"Adam Pally, T.J. Miller, Thomas Middleditch,Sh...",2014,93,5.6,4881,NaN,22.0,0
999,1000,Nine Lives,"Comedy,Family,Fantasy",A stuffy businessman finds himself trapped ins...,Barry Sonnenfeld,"Kevin Spacey, Jennifer Garner, Robbie Amell,Ch...",2016,87,5.3,12435,19.64,11.0,0

In [76]:
# df.sample(n) : selectionne de manière random n lignes de la df
df.sample(5)

,Rank,Title,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore,my_rating
712,713,The Book of Life,"Animation,Adventure,Comedy","Manolo, a young man who is torn between fulfil...",Jorge R. Gutiérrez,"Diego Luna, Zoe Saldana, Channing Tatum, Ron P...",2014,95,7.3,50388,50.15,67.0,0
340,341,Fast & Furious,"Action,Crime,Thriller","Brian O'Conner, back working for the FBI in Lo...",Justin Lin,"Vin Diesel, Paul Walker, Michelle Rodriguez, J...",2009,107,6.6,217464,155.02,46.0,0
940,941,The Midnight Meat Train,"Horror,Mystery",A photographer's obsessive pursuit of dark sub...,Ryûhei Kitamura,"Vinnie Jones, Bradley Cooper, Leslie Bibb, Bro...",2008,98,6.1,50255,0.07,58.0,0
5,6,The Great Wall,"Action,Adventure,Fantasy",European mercenaries searching for black powde...,Yimou Zhang,"Matt Damon, Tian Jing, Willem Dafoe, Andy Lau",2016,103,6.1,56036,45.13,42.0,0
503,504,Youth,"Comedy,Drama,Music",A retired orchestra conductor is on holiday wi...,Paolo Sorrentino,"Michael Caine, Harvey Keitel, Rachel Weisz, Ja...",2015,124,7.3,52636,2.70,64.0,0

In [46]:
df.shape # (nombres de lignes, nombres de colonnes)

(1000, 12)

In [47]:
df.columns # retourne tous les noms des colonnes de la DataFrame

Index(['Rank', 'Title', 'Genre', 'Description', 'Director', 'Actors', 'Year',
       'Runtime (Minutes)', 'Rating', 'Votes', 'Revenue (Millions)',
       'Metascore'],
      dtype='object')

In [48]:
df.info() # retourne des informations générales sur la df (noms colonnes, nombres de lignes, types des données...)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Rank                1000 non-null   int64
 1   Title               1000 non-null   object
 2   Genre               1000 non-null   object
 3   Description         1000 non-null   object
 4   Director            1000 non-null   object
 5   Actors              1000 non-null   object
 6   Year                1000 non-null   int64
 7   Runtime (Minutes)   1000 non-null   int64
 8   Rating              1000 non-null   float64
 9   Votes               1000 non-null   int64
 10  Revenue (Millions)  872 non-null    float64
 11  Metascore           936 non-null    float64
dtypes: float64(3), int64(4), object(5)
memory usage: 93.9+ KB

In [49]:
# Sélection d'une colonne spécifique
df["Title"].head()

0    Guardians of the Galaxy
1                 Prometheus
2                      Split
3                       Sing
4              Suicide Squad
Name: Title, dtype: object

In [50]:
# Sélection de plusieures colonnes
df[["Title","Genre","Year","Rating"]].head()

                     Title                     Genre  Year  Rating
0  Guardians of the Galaxy   Action,Adventure,Sci-Fi  2014     8.1
1               Prometheus  Adventure,Mystery,Sci-Fi  2012     7.0
2                    Split           Horror,Thriller  2016     7.3
3                     Sing   Animation,Comedy,Family  2016     7.2
4            Suicide Squad  Action,Adventure,Fantasy  2016     6.2

In [51]:
# afficher une ligne
df.loc[0]

Rank                                                                  1
Title                                           Guardians of the Galaxy
Genre                                           Action,Adventure,Sci-Fi
Description           A group of intergalactic criminals are forced ...
Director                                                     James Gunn
Actors                Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...
Year                                                               2014
Runtime (Minutes)                                                   121
Rating                                                              8.1
Votes                                                            757074
Revenue (Millions)                                               333.13
Metascore                                                          76.0
Name: 0, dtype: object

In [52]:
# plage de lignes
df.loc[0:4]

,Rank,Title,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore
0,1,Guardians of the Galaxy,"Action,Adventure,Sci-Fi",A group of intergalactic criminals are forced ...,James Gunn,"Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...",2014,121,8.1,757074,333.13,76.0
1,2,Prometheus,"Adventure,Mystery,Sci-Fi","Following clues to the origin of mankind, a te...",Ridley Scott,"Noomi Rapace, Logan Marshall-Green, Michael Fa...",2012,124,7.0,485820,126.46,65.0
2,3,Split,"Horror,Thriller",Three girls are kidnapped by a man with a diag...,M. Night Shyamalan,"James McAvoy, Anya Taylor-Joy, Haley Lu Richar...",2016,117,7.3,157606,138.12,62.0
3,4,Sing,"Animation,Comedy,Family","In a city of humanoid animals, a hustling thea...",Christophe Lourdelet,"Matthew McConaughey,Reese Witherspoon, Seth Ma...",2016,108,7.2,60545,270.32,59.0
4,5,Suicide Squad,"Action,Adventure,Fantasy",A secret government agency recruits some of th...,David Ayer,"Will Smith, Jared Leto, Margot Robbie, Viola D...",2016,123,6.2,393727,325.02,40.0

In [53]:
# filtrage
# exemple 1: on veut afficher les films sortis en 2014
df[df['Year'] == 2014]

,Rank,Title,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore
0,1,Guardians of the Galaxy,"Action,Adventure,Sci-Fi",A group of intergalactic criminals are forced ...,James Gunn,"Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...",2014,121,8.1,757074,333.13,76.0
36,37,Interstellar,"Adventure,Drama,Sci-Fi",A team of explorers travel through a wormhole ...,Christopher Nolan,"Matthew McConaughey, Anne Hathaway, Jessica Ch...",2014,169,8.6,1047747,187.99,74.0
53,54,John Wick,"Action,Crime,Thriller",An ex-hitman comes out of retirement to track ...,Chad Stahelski,"Keanu Reeves, Michael Nyqvist, Alfie Allen, Wi...",2014,101,7.2,321933,43.00,68.0
65,66,Kingsman: The Secret Service,"Action,Adventure,Comedy","A spy organization recruits an unrefined, but ...",Matthew Vaughn,"Colin Firth, Taron Egerton, Samuel L. Jackson,...",2014,129,7.7,440209,128.25,58.0
83,84,Gone Girl,"Crime,Drama,Mystery",With his wife's disappearance having become th...,David Fincher,"Ben Affleck, Rosamund Pike, Neil Patrick Harri...",2014,149,8.1,636243,167.74,79.0
...,...,...,...,...,...,...,...,...,...,...,...,...
981,982,Annie,"Comedy,Drama,Family","A foster kid, who lives with her mean foster m...",Will Gluck,"Quvenzhané Wallis, Cameron Diaz, Jamie Foxx, R...",2014,118,5.3,27312,85.91,33.0
983,984,Let's Be Cops,Comedy,Two struggling pals dress as police officers f...,Luke Greenfield,"Jake Johnson, Damon Wayans Jr., Rob Riggle, Ni...",2014,104,6.5,112729,82.39,30.0
987,988,Endless Love,"Drama,Romance",The story of a privileged girl and a charismat...,Shana Feste,"Gabriella Wilde, Alex Pettyfer, Bruce Greenwoo...",2014,104,6.3,33688,23.39,30.0
989,990,Selma,"Biography,Drama,History",A chronicle of Martin Luther King's campaign t...,Ava DuVernay,"David Oyelowo, Carmen Ejogo, Tim Roth, Lorrain...",2014,128,7.5,67637,52.07,NaN
998,999,Search Party,"Adventure,Comedy",A pair of friends embark on a mission to reuni...,Scot Armstrong,"Adam Pally, T.J. Miller, Thomas Middleditch,Sh...",2014,93,5.6,4881,NaN,22.0

In [54]:
# exemple 2: on veut afficher le film qui a le plus haut rating
df[df['Rating'] == df['Rating'].max()]

,Rank,Title,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore
54,55,The Dark Knight,"Action,Crime,Drama",When the menace known as the Joker wreaks havo...,Christopher Nolan,"Christian Bale, Heath Ledger, Aaron Eckhart,Mi...",2008,152,9.0,1791916,533.32,82.0

In [101]:
# exemple 3: en utilisant df.query("nom_col condition") , plus efficace sur des DataFrames volumineux
df.query("Director == 'Christopher Nolan'")

,Rank,Title,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore,my_rating
36,37,Interstellar,"Adventure,Drama,Sci-Fi",A team of explorers travel through a wormhole ...,Christopher Nolan,"Matthew McConaughey, Anne Hathaway, Jessica Ch...",2014,169,8.6,1047747,187.99,74.0,0
54,55,The Dark Knight,"Action,Crime,Drama",When the menace known as the Joker wreaks havo...,Christopher Nolan,"Christian Bale, Heath Ledger, Aaron Eckhart,Mi...",2008,152,9.0,1791916,533.32,82.0,0
64,65,The Prestige,"Drama,Mystery,Sci-Fi",Two stage magicians engage in competitive one-...,Christopher Nolan,"Christian Bale, Hugh Jackman, Scarlett Johanss...",2006,130,8.5,913152,53.08,66.0,0
80,81,Inception,"Action,Adventure,Sci-Fi","A thief, who steals corporate secrets through ...",Christopher Nolan,"Leonardo DiCaprio, Joseph Gordon-Levitt, Ellen...",2010,148,8.8,1583625,292.57,74.0,0
124,125,The Dark Knight Rises,"Action,Thriller",Eight years after the Joker's reign of anarchy...,Christopher Nolan,"Christian Bale, Tom Hardy, Anne Hathaway,Gary ...",2012,164,8.5,1222645,448.13,78.0,0

In [99]:
# df["colonne"].unique() retourne les valeurs unique d'une colonne
# df["colonne"].nunique() retourne le nombres des valeurs uniques d'une colonne
print(f'vals uniques de la col Year: {df["Year"].unique()}')
print(f'num de vals uniques: {df["Year"].nunique()}')

vals uniques de la col Year: [2014 2012 2016 2015 2007 2011 2008 2006 2009 2010 2013]
num de vals uniques: 11

In [55]:
# Manipulation des données
# ajouter une colonne
df['my_rating'] = 0 # valeur 0 s'applique sur tt les lignes
# ajouter/modifier une valeur en utilisant l'index: df.loc[index_ligne,'nom_col']
df.loc[0,'my_rating'] = 9
df.loc[1,'my_rating'] = 6
df.head()

,Rank,Title,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore,my_rating
0,1,Guardians of the Galaxy,"Action,Adventure,Sci-Fi",A group of intergalactic criminals are forced ...,James Gunn,"Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...",2014,121,8.1,757074,333.13,76.0,9
1,2,Prometheus,"Adventure,Mystery,Sci-Fi","Following clues to the origin of mankind, a te...",Ridley Scott,"Noomi Rapace, Logan Marshall-Green, Michael Fa...",2012,124,7.0,485820,126.46,65.0,6
2,3,Split,"Horror,Thriller",Three girls are kidnapped by a man with a diag...,M. Night Shyamalan,"James McAvoy, Anya Taylor-Joy, Haley Lu Richar...",2016,117,7.3,157606,138.12,62.0,0
3,4,Sing,"Animation,Comedy,Family","In a city of humanoid animals, a hustling thea...",Christophe Lourdelet,"Matthew McConaughey,Reese Witherspoon, Seth Ma...",2016,108,7.2,60545,270.32,59.0,0
4,5,Suicide Squad,"Action,Adventure,Fantasy",A secret government agency recruits some of th...,David Ayer,"Will Smith, Jared Leto, Margot Robbie, Viola D...",2016,123,6.2,393727,325.02,40.0,0

In [56]:
# on peut aussi utiliser df.iloc
# indexation purement basée sur des entiers pour une sélection par position
df.iloc[0,1]

'Guardians of the Galaxy'

In [57]:
df.iloc[0:5]

,Rank,Title,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore,my_rating
0,1,Guardians of the Galaxy,"Action,Adventure,Sci-Fi",A group of intergalactic criminals are forced ...,James Gunn,"Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...",2014,121,8.1,757074,333.13,76.0,9
1,2,Prometheus,"Adventure,Mystery,Sci-Fi","Following clues to the origin of mankind, a te...",Ridley Scott,"Noomi Rapace, Logan Marshall-Green, Michael Fa...",2012,124,7.0,485820,126.46,65.0,6
2,3,Split,"Horror,Thriller",Three girls are kidnapped by a man with a diag...,M. Night Shyamalan,"James McAvoy, Anya Taylor-Joy, Haley Lu Richar...",2016,117,7.3,157606,138.12,62.0,0
3,4,Sing,"Animation,Comedy,Family","In a city of humanoid animals, a hustling thea...",Christophe Lourdelet,"Matthew McConaughey,Reese Witherspoon, Seth Ma...",2016,108,7.2,60545,270.32,59.0,0
4,5,Suicide Squad,"Action,Adventure,Fantasy",A secret government agency recruits some of th...,David Ayer,"Will Smith, Jared Leto, Margot Robbie, Viola D...",2016,123,6.2,393727,325.02,40.0,0

In [88]:
# ajouter une ligne avec df.loc
# supposons qu'on veut ajouter ce film
my_movie = [
    1001, # Rank
    "Echoes of Eternity",  # Title
    "Sci-Fi, Mystery, Drama",  # Genre
    "In a dystopian future, a scientist discovers a way to record memories of the dead, uncovering secrets that could alter humanity's fate. As she dives deeper into the echoes of the past, she realizes some memories are best left forgotten.",  # Description
    "Ava Mitchell",  # Director
    "Liam Carter, Sophia Hayes, Jordan Vega, Emily Kim",  # Actors
    2300,  # Year
    "137",  # Runtime (Minutes)
    8.4, # Rating
    772193, # Votes
    422, # Revenue (Millions)
    75.0, # Metascore
    10 # My rating
]

In [89]:
df_1001 = df.copy()
df_1001.loc[1000] = my_movie
df_1001.tail(1)

,Rank,Title,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore,my_rating
1000,1001,Echoes of Eternity,"Sci-Fi, Mystery, Drama","In a dystopian future, a scientist discovers a...",Ava Mitchell,"Liam Carter, Sophia Hayes, Jordan Vega, Emily Kim",2300,137,8.4,772193,422.0,75.0,10

In [58]:
# supprimer une ligne (par exemple la première ligne)
df_no_index0 = df.drop(index = 0)
df_no_index0.head()

,Rank,Title,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore,my_rating
1,2,Prometheus,"Adventure,Mystery,Sci-Fi","Following clues to the origin of mankind, a te...",Ridley Scott,"Noomi Rapace, Logan Marshall-Green, Michael Fa...",2012,124,7.0,485820,126.46,65.0,6
2,3,Split,"Horror,Thriller",Three girls are kidnapped by a man with a diag...,M. Night Shyamalan,"James McAvoy, Anya Taylor-Joy, Haley Lu Richar...",2016,117,7.3,157606,138.12,62.0,0
3,4,Sing,"Animation,Comedy,Family","In a city of humanoid animals, a hustling thea...",Christophe Lourdelet,"Matthew McConaughey,Reese Witherspoon, Seth Ma...",2016,108,7.2,60545,270.32,59.0,0
4,5,Suicide Squad,"Action,Adventure,Fantasy",A secret government agency recruits some of th...,David Ayer,"Will Smith, Jared Leto, Margot Robbie, Viola D...",2016,123,6.2,393727,325.02,40.0,0
5,6,The Great Wall,"Action,Adventure,Fantasy",European mercenaries searching for black powde...,Yimou Zhang,"Matt Damon, Tian Jing, Willem Dafoe, Andy Lau",2016,103,6.1,56036,45.13,42.0,0

In [59]:
# supprimer une colonne entiere
df_no_rank = df.drop("Rank",axis = 1) # axis = 1 : axe vertical pour supp les colonnes, axis = 0 par defaut
df_no_rank.head()

,Title,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore,my_rating
0,Guardians of the Galaxy,"Action,Adventure,Sci-Fi",A group of intergalactic criminals are forced ...,James Gunn,"Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...",2014,121,8.1,757074,333.13,76.0,9
1,Prometheus,"Adventure,Mystery,Sci-Fi","Following clues to the origin of mankind, a te...",Ridley Scott,"Noomi Rapace, Logan Marshall-Green, Michael Fa...",2012,124,7.0,485820,126.46,65.0,6
2,Split,"Horror,Thriller",Three girls are kidnapped by a man with a diag...,M. Night Shyamalan,"James McAvoy, Anya Taylor-Joy, Haley Lu Richar...",2016,117,7.3,157606,138.12,62.0,0
3,Sing,"Animation,Comedy,Family","In a city of humanoid animals, a hustling thea...",Christophe Lourdelet,"Matthew McConaughey,Reese Witherspoon, Seth Ma...",2016,108,7.2,60545,270.32,59.0,0
4,Suicide Squad,"Action,Adventure,Fantasy",A secret government agency recruits some of th...,David Ayer,"Will Smith, Jared Leto, Margot Robbie, Viola D...",2016,123,6.2,393727,325.02,40.0,0

In [60]:
# gérer les valeurs manquantes (NaN...) 
# Cherchons les colonnes qui en contiennent
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 13 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Rank                1000 non-null   int64
 1   Title               1000 non-null   object
 2   Genre               1000 non-null   object
 3   Description         1000 non-null   object
 4   Director            1000 non-null   object
 5   Actors              1000 non-null   object
 6   Year                1000 non-null   int64
 7   Runtime (Minutes)   1000 non-null   int64
 8   Rating              1000 non-null   float64
 9   Votes               1000 non-null   int64
 10  Revenue (Millions)  872 non-null    float64
 11  Metascore           936 non-null    float64
 12  my_rating           1000 non-null   int64
dtypes: float64(3), int64(5), object(5)
memory usage: 101.7+ KB

In [61]:
# on constate que les colonnes revenue et metascore contiennent des valeurs nulles
# on décide de supprimer les lignes qui sont concernées
df_filtered = df.dropna(axis = 0) # axis = 0 par defaut 
# Si axis=1 : toutes les colonnes contenant au moins une valeur manquante seront supprimées
df_filtered.info()
# on passe de 1000 lignes à 838 lignes

<class 'pandas.core.frame.DataFrame'>
Index: 838 entries, 0 to 999
Data columns (total 13 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Rank                838 non-null    int64
 1   Title               838 non-null    object
 2   Genre               838 non-null    object
 3   Description         838 non-null    object
 4   Director            838 non-null    object
 5   Actors              838 non-null    object
 6   Year                838 non-null    int64
 7   Runtime (Minutes)   838 non-null    int64
 8   Rating              838 non-null    float64
 9   Votes               838 non-null    int64
 10  Revenue (Millions)  838 non-null    float64
 11  Metascore           838 non-null    float64
 12  my_rating           838 non-null    int64
dtypes: float64(3), int64(5), object(5)
memory usage: 91.7+ KB

In [62]:
# alternativement, on peut remplir les cases vides en utilisant df.fillna()
# pour des valeurs numériques on peut remplir en utilisant la moyenne ou la médiane des valeurs existantes
# pour les autres types de valeurs (catégoriques), on peut opter pour la valeur existante la plus fréquente
# il existe aussi df.interpolate() qui remplis les NaNs en estimant à partir de méthodes d'interpolation
df_filled = df.copy()
df_filled["Revenue (Millions)"] = df_filled["Revenue (Millions)"].fillna(df["Revenue (Millions)"].mean())
df_filled["Metascore"] = df_filled["Metascore"].fillna(df["Metascore"].mean())

df_filled.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 13 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Rank                1000 non-null   int64
 1   Title               1000 non-null   object
 2   Genre               1000 non-null   object
 3   Description         1000 non-null   object
 4   Director            1000 non-null   object
 5   Actors              1000 non-null   object
 6   Year                1000 non-null   int64
 7   Runtime (Minutes)   1000 non-null   int64
 8   Rating              1000 non-null   float64
 9   Votes               1000 non-null   int64
 10  Revenue (Millions)  1000 non-null   float64
 11  Metascore           1000 non-null   float64
 12  my_rating           1000 non-null   int64
dtypes: float64(3), int64(5), object(5)
memory usage: 101.7+ KB

In [95]:
# comment gérer les doublons?
# -> df.duplicated retourne une Series booléene : True indique qu'une ligne est doublon
# ici dans cet exemple il n'existe pas de doublons
# on peut par la suite les supprimer avec df.drop_duplicates()
df[df.duplicated()]

Empty DataFrame
Columns: [Rank, Title, Genre, Description, Director, Actors, Year, Runtime (Minutes), Rating, Votes, Revenue (Millions), Metascore, my_rating]
Index: []

In [63]:
# un peu de statistique :)
# premièrement regroupons les colonnes numériques
num_cols = ['Runtime (Minutes)', 'Rating', 'Revenue (Millions)','Metascore']
# quelques stats utiles
df[num_cols].describe()

       Runtime (Minutes)       Rating  Revenue (Millions)   Metascore
count        1000.000000  1000.000000          872.000000  936.000000
mean          113.172000     6.723200           82.956376   58.985043
std            18.810908     0.945429          103.253540   17.194757
min            66.000000     1.900000            0.000000   11.000000
25%           100.000000     6.200000           13.270000   47.000000
50%           111.000000     6.800000           47.985000   59.500000
75%           123.000000     7.400000          113.715000   72.000000
max           191.000000     9.000000          936.630000  100.000000

In [64]:
df[num_cols].corr() # affiche la correlation entre les colonnes

                    Runtime (Minutes)    Rating  Revenue (Millions)  Metascore
Runtime (Minutes)            1.000000  0.392214            0.267953   0.211978
Rating                       0.392214  1.000000            0.217654   0.631897
Revenue (Millions)           0.267953  0.217654            1.000000   0.142397
Metascore                    0.211978  0.631897            0.142397   1.000000

In [65]:
# regroupement des données par catégories
# exemple: somme revenu en millions de dollars des films par genres
revenu_par_genre = df[["Genre","Revenue (Millions)"]].groupby("Genre").sum()
revenu_par_genre.head()

                            Revenue (Millions)
Genre
Action                                  131.56
Action,Adventure                        671.22
Action,Adventure,Biography               33.00
Action,Adventure,Comedy                1340.27
Action,Adventure,Crime                  543.72

In [66]:
# tri (meme exemple)
revenu_par_genre.sort_values(by="Revenue (Millions)") # croissant par defaut

                            Revenue (Millions)
Genre
Thriller,War                              0.00
Action,Horror                             0.00
Romance,Sci-Fi                            0.00
Mystery,Thriller,Western                  0.00
Animation,Drama,Romance                   0.00
...                                        ...
Comedy                                 1941.81
Adventure,Family,Fantasy               2201.47
Action,Adventure,Fantasy               5248.29
Animation,Adventure,Comedy             5754.75
Action,Adventure,Sci-Fi               10461.51

[207 rows x 1 columns]

In [67]:
# ordre décroissant
revenu_par_genre.sort_values(by="Revenue (Millions)",ascending = False) # ascending parameter par defaut est True

                            Revenue (Millions)
Genre
Action,Adventure,Sci-Fi               10461.51
Animation,Adventure,Comedy             5754.75
Action,Adventure,Fantasy               5248.29
Adventure,Family,Fantasy               2201.47
Comedy                                 1941.81
...                                        ...
Animation,Drama,Romance                   0.00
Comedy,Sci-Fi                             0.00
Comedy,Western                            0.00
Drama,Family                              0.00
Thriller,War                              0.00

[207 rows x 1 columns]

In [68]:
# Sources:
# Dataset : https://www.kaggle.com/datasets/PromptCloudHQ/imdb-data
# Pour aller plus loin :
# Documentation Pandas : https://pandas.pydata.org/docs/getting_started/index.html